### ISSUE TITLE
Issue on ubuntu server with AWT headless

### ISSUE THREAD

**Issue by realtebo** [lord-ralf-adolf/Lordroid_One_Deodexer_To_Rule_Them_ALL#13]
I'm running with this commands

    java -jar Launcher.jar --config j=2
    java -jar Launcher.jar <full_path_to_/system> z 

```
java.lang.ExceptionInInitializerError
        at com.alee.laf.progressbar.WebProgressBarUI.updateBorder(WebProgressBarUI.java:159)
        at com.alee.laf.progressbar.WebProgressBarUI.installUI(WebProgressBarUI.java:101)
        at javax.swing.JComponent.setUI(JComponent.java:666)
        at javax.swing.JProgressBar.setUI(JProgressBar.java:609)
        at com.alee.laf.progressbar.WebProgressBar.updateUI(WebProgressBar.java:215)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:334)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:274)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:251)
        at com.alee.laf.progressbar.WebProgressBar.<init>(WebProgressBar.java:43)
        at deodex.controlers.ApkWorker.<init>(ApkWorker.java:63)
        at deodex.controlers.MainWorker.init(MainWorker.java:289)
        at deodex.controlers.MainWorker.<init>(MainWorker.java:92)
        at deodex.Main.proseedWithNoGui(Main.java:368)
        at deodex.Main.argsReader(Main.java:115)
        at deodex.Main.main(Main.java:213)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:77)
        at com.alee.utils.SystemUtils.getGraphicsConfiguration(SystemUtils.java:483)
        at com.alee.utils.ImageUtils.createCompatibleImage(ImageUtils.java:72)
        at com.alee.utils.ImageUtils.getBufferedImage(ImageUtils.java:1046)
        at com.alee.utils.ImageUtils.getBufferedImage(ImageUtils.java:1027)
        at com.alee.utils.ImageUtils.getBufferedImage(ImageUtils.java:1017)
        at com.alee.utils.ninepatch.NinePatchIcon.<init>(NinePatchIcon.java:110)
        at com.alee.utils.ninepatch.NinePatchIcon.<init>(NinePatchIcon.java:99)
        at com.alee.utils.LafUtils.<clinit>(LafUtils.java:998)
        ... 15 more
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.alee.utils.LafUtils
        at com.alee.laf.progressbar.WebProgressBarUI.updateBorder(WebProgressBarUI.java:159)
        at com.alee.laf.progressbar.WebProgressBarUI.installUI(WebProgressBarUI.java:101)
        at javax.swing.JComponent.setUI(JComponent.java:666)
        at javax.swing.JProgressBar.setUI(JProgressBar.java:609)
        at com.alee.laf.progressbar.WebProgressBar.updateUI(WebProgressBar.java:220)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:334)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:274)
        at javax.swing.JProgressBar.<init>(JProgressBar.java:251)
        at com.alee.laf.progressbar.WebProgressBar.<init>(WebProgressBar.java:43)
        at deodex.controlers.ApkWorker.<init>(ApkWorker.java:63)
        at deodex.controlers.MainWorker.init(MainWorker.java:289)
        at deodex.controlers.MainWorker.<init>(MainWorker.java:92)
        at deodex.Main.proseedWithNoGui(Main.java:368)
        at deodex.Main.argsReader(Main.java:115)
        at deodex.Main.main(Main.java:213)

```

**Comment by lord-ralf-adolf** [comment]
this is due to x-server dependency working on a fix for this ,need to separate the gui from the command line tools to prevent this

**Comment by realtebo** [comment]
Ok, I close this Issue with a usefull and easy workaround we use on our VPS (Ubuntu 16.04 x64)

We installed a sort of 'x emulator' 

    sudo apt-get install -y xvfb blackbox

then in etc/profile we added

    export DISPLAY=:1
    Xvfb :1 -screen 0 1024x768x16 &

After reboot, your tool is working without a glitch.
